apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.secretStoreName }}
spec:
  conditions:
    - namespaceSelector:
        matchLabels:
          eso: enabled
  provider:
    kubernetes:
      remoteNamespace: {{ .Values.secretsNamespace }}
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          namespace: {{ .Values.secretsNamespace }}
          key: ca.crt
      auth:
        serviceAccount:
          name: my-remote-sa
          namespace: {{ .Values.secretsNamespace }}