apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.secretStoreName }}
spec:
  provider:
    kubernetes:
      remoteNamespace: {{ .Values.secretsNamespace }}
      server:
        #url: "{{ .Values.clusterIP }}"
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          namespace: {{ .Values.targetNamespace }}
          key: ca.crt
      auth:
        serviceAccount:
          name: my-remote-sa
          namespace: {{ .Values.secretsNamespace }}