---
apiVersion: v1
kind: Secret
metadata:
  name: secret-one # name of the secret
  namespace: remote-cluster
data:
  the-key: c2VjcmV0LXZhbHVl # secret key/value pair
type: Opaque
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: data-by-name
  namespace: {{ .Values.targetNamespace }}
spec:
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.secretStoreName }}

  target:
    name: data-by-name
    creationPolicy: Owner

  data:
    - secretKey: secret-value
      remoteRef:
        key: secret-one # name of the secret
        property: "the-key" # key in the secret